name: Python CI

on:
  push:
    branches:
      - main
      - week3-cicd
    paths-ignore:
      - "README.md"
      - "**/*.md"

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: week03-cicd/projects/github-actions-python-demo

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: run linter
        run: |
          ruff check .

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: week03-cicd/projects/github-actions-python-demo

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests
        run: python -m pytest -v

  validate:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: week03-cicd/projects/github-actions-python-demo

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run validation tests
        run: |
          python -c "from app.validator import validate_environment; assert validate_environment('production')"

  build:
    needs:
      - lint
      - test
      - validate

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: week03-cicd/projects/github-actions-python-demo

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
     
      - name: Build ready
        run: echo "All validation jobs passed. Ready to build."

      - name: Upload build report
        uses: actions/upload-artifact@v4
        with:
            name: build-report
            path: projects/github-actions-python-demo/reports/build-report.txt